from abc import ABC, abstractmethod
from typing import List, Dict
from langchain_core.documents import Document


class BaseVectorStore(ABC):
    '''
    Abstract base interface for all vector store backends.

    This class defines a unified contract for interacting with different
    vector databases (e.g. Qdrant, FAISS, Pinecone, Weaviate).
    By programming against this interface, higher-level application
    code remains decoupled from any specific vector database implementation.

    Implementations of this interface are expected to:
    - Handle vector insertion (embedding + metadata storage)
    - Perform semantic similarity search
    - Be compatible with LangChain's `Document` abstraction

    This design follows the Adapter pattern and enables:
    - Easy backend replacement
    - Clean dependency inversion
    - Scalable RAG and retrieval architectures
    '''

    @abstractmethod
    def upsert_documents(self, documents: List[Document]) -> None:
        '''
        Add or upsert documents into the vector store.

        Implementations must:
        - Generate embeddings from `Document.page_content`
        - Store vectors in the underlying vector database
        - Persist document metadata as payloads or attributes

        Parameters
        ----------
        documents : List[langchain_core.documents.Document]
            A list of LangChain `Document` objects to be stored.

            Each document should contain:
            - page_content : str
                The textual content used for embedding generation
            - metadata : dict
                Arbitrary key-value metadata associated with the document

        Returns
        -------
        None

        Notes
        -----
        - Implementations may perform batching internally
        - Document IDs may be auto-generated by the backend
        - Embedding normalization behavior depends on the backend configuration
        '''
        raise NotImplementedError

    @abstractmethod
    def search(self, query: str, limit: int = 5) -> List[Dict]:
        '''
        Perform semantic similarity search using a text query.

        This method converts the input query into an embedding vector
        and retrieves the most semantically similar documents from the
        vector database.

        Parameters
        ----------
        query : str
            The input text query used for semantic search.
        limit : int, default=5
            The maximum number of search results to return.

        Returns
        -------
        List[Dict]
            A list of result dictionaries, each containing:
            - content : str
                The document text
            - metadata : dict
                Associated document metadata
            - score : float
                Similarity score between the query and the document

        Notes
        -----
        - Higher scores indicate stronger semantic similarity
        - The similarity metric (e.g. cosine, dot-product) is backend-specific
        - Result ordering must be descending by similarity score
        '''
        raise NotImplementedError
